ДЗ 2
zaitsev998/2020-2-Atom-QA-Python-A-Zaitsev pull request #5
Opened 2020-10-19 19:10 UTC by zaitsev998

# Домашнее задание №

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
Написана фикстура для авторизации
Написаны позитивный и негативный тесты на авторизацию
Написаны тесты на создание и удаление сегментов
Предпринята попытка написания теста на создание кампании
Код реализован на паттерне PageObject
Тесты запускаются через selenium
Тесты могут запускаться параллельно

(второй PR для ДЗ 2)

2020-10-25 13:16 UTC, snicks92 requested changes
Хорошая работа, давай сделаем еще чуть чуть лучше и зачту

2020-10-25 13:16 UTC, snicks92 commented on hw2/tests/test_my_target.py
> +        self.campaigns_page.click(self.campaigns_page.locators.CREATE_CAMPAIGN_LAST_BUTTON)
Я бы вынес это в отдельную пейджу Campaign

2020-10-25 13:16 UTC, snicks92 commented on hw2/tests/test_my_target.py
> +            self.campaigns_page.click(self.campaigns_page.locators.CREATE_CAMPAIGN_BUTTON)
А это бы вынес в main_page

2020-10-25 13:25 UTC, snicks92 commented
Только сейчас заметил что тестов то изначально не было и добавились они только вчера, поэтому максимальный балл будет 8, правила есть правила

2020-10-25 13:35 UTC, zaitsev998 commented
Извините, но это уже второй pr по данному дз. 

Кирилл Солдатов уже смотрел мою работу, и при заливе исправлений я накосячил с ветками. Мне пришлось создать новый pr, куда по непонятной причине не попал файл с тестами. 

Прикладываю комментарий Кирилла. Думаю, он подтверждает, что в первом pr  файл с тестами был.

Извините за мою некомпетентность. Совсем мало работал с гитом. ![Screenshot_2020-10-25-16-31-55-179_com.android.chrome.jpg](https://user-images.githubusercontent.com/63260559/97108687-2427b700-16e0-11eb-995b-c4dc1264e56d.jpg)

2020-10-25 13:37 UTC, snicks92 commented
ок, тогда сорри за наезд)

2020-10-25 15:09 UTC, SK1995 commented
Да, тут я виноват, что очень долго проверял, прошу прощения.
Файл с тестами действительно был закоммичен давно, просто в этом PR его сначала не было, я попросил его добавить.
Ну раз уже все равно Илья посмотрел, давайте ориентироваться на его комментарии, и после их фикса PR замержим :)

2020-10-26 22:23 UTC, snicks92 approved these changes

2020-10-26 22:23 UTC, merged